[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pythonic-fp"
version = "5.1.0"
description = "Pythonic FP homepage - for packagers/forkers."
readme = "README.md"
requires-python = ">=3.14"
authors = [
  { name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" },
]
keywords = [
  "functional",
  "pythonic",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
dependencies = []

[project.urls]
Changelog = "https://github.com/grscheller/pythonic-fp/blob/main/CHANGELOG.md"
Homepage = "https://grscheller.github.io/pythonic-fp"
Source = "https://github.com/grscheller/pythonic-fp"

[dependency-groups]
docs = [
  "furo>=2025.12.19",
  "sphinx>=9.1",
]
pub = [
  "flit",
]
test = [
  "pytest>=8.4.1",
  "pythonic-fp-booleans",
  "pythonic-fp-circulararray",
  "pythonic-fp-containers",
  "pythonic-fp-fptools",
  "pythonic-fp-gadgets",
  "pythonic-fp-iterables",
  "pythonic-fp-numpy",
  "pythonic-fp-queues",
  "pythonic-fp-splitends",
]

[tool.flit.sdist]
exclude = [
  "docs/",
]

[tool.flit.module]
name = "pythonic_fp.homepage"

[tool.pytest]
addopts = ["-ra"]
consider_namespace_packages = true
testpaths = ["tests/"]

[tool.mypy]
explicit_package_bases = true
local_partial_types = true
namespace_packages = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.ruff]
target-version = "py314"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "E731",
  "C901",
]

[tool.ruff.format]
quote-style = "single"
docstring-code-line-length = 72
