# Copyright 2023-2025 Geoffrey R. Scheller
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

__all__ = ['Box']

from collections.abc import Callable, Iterator
from typing import ClassVar, Final, Never, overload, TypeVar
from pythonic_fp.sentinels.sentinel import Sentinel

D = TypeVar('D')


class Box[D]:
    __slots__ = ('_item',)
    __match_args__ = ('_item',)

    _sentinel: Final[ClassVar[Sentinel[str]]]

    T = TypeVar('T')

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: D) -> None: ...
    def __init__(self, value: D | Sentinel[str]) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[D]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    @overload
    def get(self) -> D | Never: ...
    @overload
    def get(self, alt: D) -> D: ...
    def get(self, alt: D | Sentinel[str]) -> D | Never: ...
    def pop(self) -> D | Never: ...
    def push(self, item: D) -> None | Never: ...
    def put(self, item: D) -> None: ...
    def exchange(self, new_item: D) -> D | Never: ...
    def map[T](self, f: Callable[[D], T]) -> 'Box[T]': ...
    def bind[T](self, f: Callable[[D], 'Box[T]']) -> 'Box[T]': ...
