
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["homepage"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Select Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install sphinx dependencies
        run: pip install -r docs/requirements.txt

      - name: Build homepage
        run: |
          pip install pythonic-fp
          sphinx-build -M html docs/source docs/homepage/build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
        id: deployment
